---
title: "ConnorPractice"
author: "Connor McCaughan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
library(tidycensus)
library(tidyverse)
library(dplyr)
library(scales)
```

```{r census_key, include = FALSE}
census_api_key("3256bc5e0343cacd70f9f681995f33050910c491", install = TRUE, overwrite = TRUE)
readRenviron('~/.Renviron')
```

```{r get_state_income}
state_income = get_acs(
  geography = 'state',
  variables = c(medincome = "B19013_001"),
  year = 2021
  )

head(state_income)
```

```{r plot_income, echo = FALSE, fig.width = 10, fig.height = 6}
state_income %>%
  ggplot(aes(x = reorder(NAME, estimate), y = estimate, fill = estimate)) +
  geom_col() +
  scale_fill_gradient(low = "lightblue", high = "darkblue") +
  theme_minimal() +
  labs(
    x = 'State/Territory',
    y = 'Median Household Income',
    title = 'Median Household Income by State (ACS 2021)'
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r get_city_income, include = FALSE}
places <- get_acs(
  geography = 'place',
  variables = c(medincome = "B01003_001"),
  year = 2021
)

large_cities <- places %>%
  filter(estimate > 700000 & estimate < 5000000)
```

```{r plot_city_income}
large_cities %>%
  ggplot(aes(x = reorder(NAME, -estimate), y = estimate, fill = estimate)) +
  geom_col() +
  labs(
    x = "Place Name",
    y = "Median Household Income",
    title = "Median Household Income by Cities with Population > 700,000"
    ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(labels = comma)
```

```{r get_city_med_income, include = FALSE}
pop_data <- get_acs(
  geography = 'place',
  variable = c(population = 'B01003_001'),
  year = 2021
)

income_data <- get_acs(
  geography = 'place',
  variable = c(medincome = 'B19013_001'),
  year = 2021
)

city_data <- pop_data %>%
  select(GEOID, NAME, population = estimate) %>%
  left_join(
    income_data %>%
      select(GEOID, medincome = estimate),
    by = 'GEOID'
  )
```

```{r clean_city_names}
high_pop_cities <- city_data %>%
  filter(population > 700000 & population < 5000000) %>%
  mutate(
    NAME = gsub(' city,.*', '', NAME)
  )
```

```{r get_us_medincome}
us_income <- get_acs(
  geography = 'us',
  variables = c(us_medincome = 'B19013_001'),
  year = 2021
)

national_median <- us_income$estimate
```

```{r high_pop_city_plot}
ggplot(high_pop_cities, aes(x = reorder(NAME, -population), y = medincome, fill = population)) +
  geom_col()+
  scale_fill_gradient(low = 'lightpink', high = 'darkblue', labels = scales::comma) +
  labs(
    x = 'City (Ordered by Population Size, high to low)',
    y = 'Median Household Income',
    title = 'Median Household Income in Cities with Population > 700,000'
  ) +
  geom_text(
    aes(label = scales::comma(population)),
    position = position_stack(vjust = 0.33),
    angle = 90,
    color = 'white',
    size = 3
  ) +
  geom_hline(
    yintercept = national_median,
    linetype = 'dashed',
    color = 'red'
  ) +
  annotate(
    'text',
    x = 10,
    y = national_median + 5000,
    label = paste0('U.S. Median: $', scales::comma(national_median)),
    color = 'black',
    size = 3
    ) +
  scale_y_continuous(labels = comma) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = -45, hjust = 0))
```

```{r get_gross_rent_by_state}
state_gross_rent <- get_acs(
  geography = 'state',
  variables = c('gross_rent' = 'B25064_001'),
  year = 2021
)
```
```{r get_monthly_med_income}
monthly_med_inc <- national_median/12
```

```{r get_us_med_gross_rent}
national_med_rent <- get_acs(
  geography = 'us',
  variables = 'B25064_001',
  year = 2021
)

us_gross_med_rent <- national_med_rent$estimate
```

```{r calc_min_wage}
fed_min_wage = 7.25
monthly_wage_min = ((fed_min_wage * 40) * 52)/12
```

```{r plot_state_gross_rent}
state_gross_rent %>%
  ggplot(aes(x = reorder(NAME, -estimate), y = estimate, fill = estimate)) +
  geom_col() +
  labs(x = 'State',
       y = 'Gross Median Rent ($)',
       title = 'Gross Median Rent by State') +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  scale_y_continuous(labels = scales::dollar) +
  scale_fill_continuous(
    low = 'lightblue',
    high = 'darkblue',
    labels = scales::dollar,
    name = 'Median Rent ($)'
  )
  geom_hline(
    yintercept = round(us_gross_med_rent),
    linetype = 'dashed',
    color = 'red'
  ) +
  geom_hline(
    yintercept = monthly_wage_min,
    linetype = 'dashed',
    color = 'green2'
  ) +
  annotate(
    'text',
    x = 26,
    y = monthly_wage_min + 60,
    label = paste0('Federal Monthly Minimum Wage (Full-time): ', scales::dollar(monthly_wage_min)),
    color = 'black',
    size = 3
  ) +
  annotate(
    'text',
    x = 26,
    y = us_gross_med_rent + 60,
    label = paste0('U.S. Monthly Median : $', scales::comma(us_gross_med_rent)),
    color = 'black',
    size = 3
  ) 
```
```{r get_big_cities, include = FALSE}
years <- c(2005:2019, 2021:2023)
get_big_city <- function(year) {
  pop <- get_acs(
    geography = 'place',
    variables = c(pop = 'B01003_001'),
    year = year,
    survey = 'acs1'
  )
  pop %>%
    filter(estimate > 700000) %>%
             select(GEOID, NAME, population = estimate) %>%
             mutate(year = year)
}
big_cities <- map_df(years, get_big_city)
```

```{r get_tenure, include = FALSE} 
owner <- 'B25003_002'
renter <- 'B25003_003'
total <- 'B25003_001'
get_tenure <- function(year) {
  tenure <- get_acs(
    geography = 'place',
    variables = c(renter_occupied = renter, owner_occupied = owner, total_occupied = total),
    year = year,
    survey = 'acs1'
  ) %>%
    select(GEOID, variable, estimate) %>%
    pivot_wider(names_from = variable, values_from = estimate) %>%
    mutate(
      year = year,
      owner_pct = owner_occupied/total_occupied,
      renter_pct = renter_occupied/total_occupied
    )
}

tenure_all <- map_df(years, get_tenure)
tenure_big <- tenure_all %>%
  inner_join(big_cities %>% select(GEOID, year), by = c("GEOID", 'year'))
```

```{r get_median_gross_rent, include = FALSE}
med_gross_rent <- 'B25064_001'
```

```{r get_med_monthly_homeowner_costs, include = FALSE}
monthly_ho_cost <- 'B25088_002'
```

```{r get_costs, include = FALSE} 
get_costs <- function(year) {
  costs <- get_acs(
    geography = 'place',
    variables = c(rent = med_gross_rent,
                  owner_cost = monthly_ho_cost),
    year = year,
    survey = 'acs1'
  ) %>%
    select(GEOID, variable, estimate) %>%
    pivot_wider(names_from = variable, values_from = estimate) %>%
    mutate(year = year)
}

costs_all <- map_df(years, get_costs)
costs_big <- costs_all %>%
  inner_join(big_cities %>%
               select(GEOID, year),
             by = c("GEOID", "year"))
```

```{r aggregate_years, include = FALSE} 
tenure_summary <- tenure_big %>%
  group_by(year) %>%
  summarize(
    owner_pct = median(owner_pct, na.rm = TRUE),
    renter_pct = median(renter_pct, na.rm = TRUE)
  )

cost_summary <- costs_big %>%
  group_by(year) %>%
  summarize(
    median_rent = median(rent, na.rm = TRUE),
    median_owner_cost = median(owner_cost, na.rm = TRUE)
  )

final_data <- tenure_summary %>%
  left_join(cost_summary, by = 'year')

```

```{r scaling} 
scale_factor <- max(final_data$median_rent, final_data$median_owner_cost)/
                max(final_data$owner_pct + final_data$renter_pct)
  

final_data <- final_data %>%
  mutate(
    rent_scaled = median_rent/scale_factor,
    owner_cost_scaled = median_owner_cost/scale_factor
    )

final_long <- final_data %>%
  pivot_longer(
    cols = c(owner_pct, renter_pct),
    names_to = "tenure_type",
    values_to = 'percent'
  ) %>%
  mutate(tenure_type = recode(tenure_type,
                              owner_pct = "Owner",
                              renter_pct = "Renter"))

final_long <- final_long %>%
  mutate(percent = percent * 100)

```

```{r mortgage} 
ggplot(final_long, aes(x = factor(year), y = percent, fill = tenure_type)) +
  geom_col() +
  geom_line(data = final_data,
            aes(x= factor(year), y = rent_scaled, color = "Median Rent"), 
            size = 1,
            inherit.aes = FALSE) +
  geom_line(data = final_data,
            aes(x = factor(year), y = owner_cost_scaled, color = "Median Owner Cost"), 
            size = 1,
            inherit.aes = FALSE) +
  scale_y_continuous(
    name = "Occupancy Type (%)",
    sec.axis = sec_axis(~. * scale_factor, name = "Cost ($)")
  ) +
  theme_minimal()+
  scale_fill_manual(values = c("Owner" = "skyblue", "Renter" = "orange")) +
  scale_color_manual(values = c("Median Rent" = "red", "Median Owner" = "darkgreen")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
 
```

##Mortage vs Rental Trends
This graph shows the proportion of owner-occupied hosuing units to renter-occupied housing units with overlays of median rent price and median monthly homeowner costs from 2005 to 2023.













